# Generated by Django 4.2.1 on 2023-05-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_jobe_title_profileemployment_job_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileCertifications", new_name="ProfileCertification",
        ),
    ]
