# Generated by Django 4.2.1 on 2023-05-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_profilecertifications_profilecertification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileprojectimage", old_name="product", new_name="profile",
        ),
    ]
