# Generated by Django 4.2 on 2023-05-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profileproject_profile_bio_profileskills_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileCertificates", new_name="ProfileCertifications",
        ),
        migrations.RenameModel(old_name="ProfileSkills", new_name="ProfileSkill",),
        migrations.AlterModelOptions(
            name="profilecertifications", options={"ordering": ("-date_achieved",)},
        ),
        migrations.AlterModelOptions(
            name="profileeducation", options={"ordering": ("-date_achieved",)},
        ),
        migrations.AlterModelOptions(
            name="profileemployment", options={"ordering": ("-date_started",)},
        ),
    ]
