# Generated by Django 4.2.1 on 2023-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_profilecertificates_profilecertifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
