# Generated by Django 4.2.1 on 2023-05-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_product_profileprojectimage_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileprojectimage',
            old_name='profile',
            new_name='project',
        ),
    ]
