# Generated by Django 4.2 on 2023-05-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_product_creator_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
